"""empty message

Revision ID: 11eea64418fe
Revises: 77434f725070
Create Date: 2021-02-11 17:10:05.730230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11eea64418fe'
down_revision = '77434f725070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'password_hash',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_constraint('ingredient_ibfk_1', 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'recipeingredients', ['recipe'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key('ingredient_ibfk_1', 'ingredient', 'recipe', ['recipe'], ['id'])
    op.alter_column('contact', 'password_hash',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
