"""empty message

Revision ID: 2375b9d1f7da
Revises: 6650a461a709
Create Date: 2021-02-10 11:34:44.930377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2375b9d1f7da'
down_revision = '6650a461a709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'score',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'score',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
