"""empty message

Revision ID: 252892f224c0
Revises: c2a5d9cba5bc
Create Date: 2021-01-27 22:14:27.576358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252892f224c0'
down_revision = 'c2a5d9cba5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('full_name', table_name='contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('full_name', 'contact', ['full_name'], unique=True)
    # ### end Alembic commands ###
