"""empty message

Revision ID: 4828a1365b5d
Revises: 11eea64418fe
Create Date: 2021-02-11 17:47:45.424726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4828a1365b5d'
down_revision = '11eea64418fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_ibfk_1', 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('recipe', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ingredient_ibfk_1', 'ingredient', 'recipeingredients', ['recipe'], ['recipe_id'])
    # ### end Alembic commands ###
