"""empty message

Revision ID: 49e42f7a485e
Revises: 662039653b12
Create Date: 2021-02-12 15:27:12.148443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49e42f7a485e'
down_revision = '662039653b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipeingredients', 'units')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipeingredients', sa.Column('units', mysql.DECIMAL(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###
