"""empty message

Revision ID: 529733404103
Revises: c749f3f092e9
Create Date: 2021-02-06 02:53:10.001413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529733404103'
down_revision = 'c749f3f092e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ingredient', sa.String(length=120), nullable=False),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('name_ingredient')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.Column('img_url', sa.String(length=250), nullable=False),
    sa.Column('tags', sa.String(length=250), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('img_url')
    )
    op.create_table('association_recipe_ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_recipe_ingredient')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
