"""empty message

Revision ID: 531d9cb3dc4b
Revises: 4207a208f755
Create Date: 2021-01-27 21:33:03.600049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531d9cb3dc4b'
down_revision = '4207a208f755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'contact', ['full_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_column('contact', 'full_name')
    # ### end Alembic commands ###
