"""empty message

Revision ID: 7f5720f6b92c
Revises: be3eee445bae
Create Date: 2021-02-10 12:47:09.997522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f5720f6b92c'
down_revision = 'be3eee445bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('recipe', sa.Integer(), nullable=True))
    op.drop_constraint('ingredient_ibfk_1', 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'recipe', ['recipe'], ['id'])
    op.drop_column('ingredient', 'recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('recipes', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key('ingredient_ibfk_1', 'ingredient', 'recipe', ['recipes'], ['id'])
    op.drop_column('ingredient', 'recipe')
    # ### end Alembic commands ###
