"""empty message

Revision ID: b503327873ca
Revises: c749f3f092e9
Create Date: 2021-02-06 20:49:32.701547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b503327873ca'
down_revision = 'c749f3f092e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('contact', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('contact', sa.Column('password_hash', sa.String(length=250), nullable=False))
    op.add_column('contact', sa.Column('salt', sa.String(length=16), nullable=False))
    op.add_column('contact', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('contact', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'contact', ['username'])
    op.drop_column('contact', 'full_name')
    op.drop_column('contact', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('password', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('contact', sa.Column('full_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_column('contact', 'username')
    op.drop_column('contact', 'status')
    op.drop_column('contact', 'salt')
    op.drop_column('contact', 'password_hash')
    op.drop_column('contact', 'name')
    op.drop_column('contact', 'last_name')
    # ### end Alembic commands ###
