"""empty message

Revision ID: be3eee445bae
Revises: 2375b9d1f7da
Create Date: 2021-02-10 12:43:58.477780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be3eee445bae'
down_revision = '2375b9d1f7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipeingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id', 'ingredient_id', 'recipe_id')
    )
    op.drop_table('recipe_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredients',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='recipe_ingredients_ibfk_1'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='recipe_ingredients_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recipeingredients')
    # ### end Alembic commands ###
