"""empty message

Revision ID: e41fa7dbfe3b
Revises: 252892f224c0
Create Date: 2021-01-27 22:40:21.944967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e41fa7dbfe3b'
down_revision = '252892f224c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
